# docker-compose.yaml
version: '3'
services:
  airflow:
    image: apache/airflow:2.7.1
    ports:
      - "8001:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./outputs:/tmp
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: standalone

